name: ShadowUI
version: ${project.version}
main: uk.co.tmdavies.shadowui.ShadowUI
api-version: 1.17
authors: [ Carbonate ]
softdepend: [ PlaceholderAPI ]
description: An All-in-One Server UI Plugin
website: https://www.tmdavies.co.uk
commands:
  shadowui:
    aliases: [ sui ]
permissions:
  shadowui.admin:
    default: op
  shadowui.customtabname:
    default: op